#!/usr/bin/bash

OUTPUT_NAME="output"
NEXT_IS_OUTPUT=0
CC=xelatex
ARGS=()
PICS=()

for item in "$@"; do
    if [ ${NEXT_IS_OUTPUT} = 1 ]; then
        item=${item%.*}
        OUTPUT_NAME=${item}
        NEXT_IS_OUTPUT=0
        continue
    fi
    if [ ${item} = "-o" ]; then
        NEXT_IS_OUTPUT=1
        continue
    fi
    if [[ ${item} =~ ^--CC= ]]; then
        item=${item##*=}
        CC=${item}
        continue
    fi
    if [[ ${item} =~ ^- ]]; then
        ARGS+=(${item})
        continue
    fi
    if [[ ${item} =~ ^(./)?\*. ]]; then
        suffix=${item##*.}
        case ${suffix} in
            png|jpg|jpeg|gif)
            ;;
            *)
                printf "Suffix '%s' is not for pictures.\n" ${suffix}
                exit 91
                ;;
        esac

        while IFS= read -r -d '' file; do
            PICS+=("$file")
        done < <(find . -type f -name "*.${suffix}" -print0)
        
        continue
    fi
    if ! [ -f ${item} ]; then
        printf "File '%s' does not exist.\n" ${item}
        exit 69
    fi

    case ${item} in
        *.png|*.jpg|*.jpeg|*.gif)
            PICS+=(${item})
            ;;
        *)
            printf "File '%s' is not a picture.\n" ${item}
            exit 91
            ;;
    esac
done

if [ -f ${OUTPUT_NAME}.tex ]; then
    rm ${OUTPUT_NAME}.tex
fi

printf '\\documentclass{article}\n' >> ${OUTPUT_NAME}.tex
printf '\\usepackage{graphicx}\n' >> ${OUTPUT_NAME}.tex
printf '\n' >> ${OUTPUT_NAME}.tex

printf '\\begin{document}\n' >> ${OUTPUT_NAME}.tex
printf '\n' >> ${OUTPUT_NAME}.tex

for item in ${PICS[@]}; do
    printf '\\begin{figure}[htbp]
  \\centering
  \\includegraphics[width=1.0\\textwidth]{%s}
\\end{figure}\n' ${item} >> ${OUTPUT_NAME}.tex
    printf '\n' >> ${OUTPUT_NAME}.tex
done

printf '\\end{document}\n' >> ${OUTPUT_NAME}.tex

${CC} ${OUTPUT_NAME}.tex ${ARGS[@]}
